### ISSUE TITLE
Yahoo API V1 does not work anymore

### ISSUE THREAD

**Issue by BasEmmen** [adafruit/Weather-Pixels#1]
Yahoo changed their API to a version with key auth. per January 2019
https://developer.yahoo.com/weather/documentation.html

**Comment by ladyada** [comment]
ahh it happens - can you try to adapt the code to add API via a #define and submit a PR? we don't have this set up at the time

**Comment by BasEmmen** [comment]
Hi there,

I was looking trough the new API details. They are a "bit" over my head.
Yahoo now works with authentication.
https://developer.yahoo.com/weather/

this is too difficult for me. I will look into forums to find people with
similar problems
I'm totally in love with my weather cloud based on the Adafruit Huzzah and
neopixels. :-)

My first
https://www.youtube.com/watch?v=22DidegCnWI

My clouds
https://www.youtube.com/watch?v=uZZIULByLFc

Greetings from The Netherlands,
Sebasitan


Op zo 6 jan. 2019 om 22:46 schreef ladyada <notifications@github.com>:

**Comment by BasEmmen** [comment]
I changed the project to work with Openweathermap.org instead of Yahoo Weather API
https://github.com/BasEmmen/Weather-Pixels

**Release notes:**
This is a modified version of the Adafruit Weather Lamp which used Yahoo Weather API before (Weather data and timestamp)
Yahoo weather API does not work anymore. This version works with Openweathermap instead.
info: https://openweathermap.org/current
Openweathermap does not parse the currenttime. (only the moment where a weather change occurred.) this version uses pool.ntp.org
Also changed the weather code id for each scenario to match Openweathermap codes: https://openweathermap.org/weather-conditions

**Comment by ladyada** [comment]
cool - wanna submit a PR change to this repo? then others can try it!

**Comment by BasEmmen** [comment]
Yes of course. Its for everybody to use.
I tested it with multiple ESP boards. Works fine. At this moment i have 5
Huzzah running it.

regards,
Bas Emmen

Op di 15 jan. 2019 om 20:39 schreef ladyada <notifications@github.com>:

**Comment by BasEmmen** [comment]
Ladyada, here is all info and repository to update the article. the Word-document has updated text for the learning system article together with a screenshot image, together with the files for you to deploy to github. 
https://www.dropbox.com/sh/90nowgsvsn4vkq1/AACG9oBX2kZZM7YoPVLA6V31a?dl=0
